apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: orderflow
  labels:
    app.kubernetes.io/name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: orderflow/inventory-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
              name: http
          envFrom:
            - configMapRef:
                name: orderflow-config
          env:
            - name: PORT
              value: "3003"
            - name: OTEL_SERVICE_NAME
              value: inventory-service
            - name: KAFKA_CONSUMER_GROUP
              value: inventory-service
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: orderflow-secrets
                  key: DATABASE_URL_INVENTORY
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: "250m"
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: orderflow
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: inventory-service
  ports:
    - name: http
      port: 3003
      targetPort: http
